name: tdd
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get_it: ^6.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  dartz: ^0.9.2
  connectivity: ^3.0.3
  http: ^0.13.1
  shared_preferences: ^2.0.5
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.2
flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
